FROM node:20-alpine3.17 
RUN curl -X GET -k -i 'https://api.github.com/repos/eclipse-theia/theia/git/refs/heads/master'
ADD https://api.github.com/repos/eclipse-theia/theia/git/refs /tmp/branch_info.json


